### PR TITLE
Fix building scripts

### PR DESCRIPTION
**Pull request by LipuFei**
Fix building scripts for windows

### CODE REVIEW

**Comment by LipuFei** [comment]
@badrock Ready to be merged.

**Comment by badrock** [comment]
@LipuFei Could you rebase you branch and apply your patch on top of it?
There is quite a lot of redundant code and it would be nice to see what the actual fix is.
Only for SConstruct of course.
Thanks

**Comment by LipuFei** [comment]
@badrock I've changed SConstruct to Windows format. Now you should be able to see the changes. :)

**Comment by badrock** [comment]
@LipuFei Thanks, it's clearer now.
I'll merge it, but please check that it works properly both on linux and mac even without the hard-coded paths (e.g. libevent from main repo should now work on modern distros)

**Pull request merged**
